'use client';

import { useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

export default function HomePage() {
  const { status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === 'authenticated') {
      router.replace('/feed');
    }
  }, [status, router]);

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Top Navigation */}
      <header className="border-b border-gray-800/60 bg-black/30 backdrop-blur">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 rounded bg-white text-black grid place-items-center font-bold">AI</div>
            <span className="text-lg font-semibold tracking-tight">News</span>
          </div>
          <nav className="flex items-center gap-3">
            <Link href="/login" className="px-4 py-2 rounded-md font-medium text-white/90 hover:text-white">
              Log In
            </Link>
            <Link href="/signup" className="px-4 py-2 rounded-md font-medium bg-white text-black hover:bg-gray-200">
              Sign Up
            </Link>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <main className="container mx-auto px-4">
        <section className="py-20 md:py-28 text-center">
          <div className="mx-auto max-w-3xl">
            <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight">
              Your personalized, AI‑curated news feed
            </h1>
            <p className="mt-4 md:mt-6 text-lg md:text-xl text-gray-300">
              Stay ahead with distilled insights from top sources. We fetch, summarize, and categorize news so you can focus on what matters.
            </p>
            <div className="mt-8 flex items-center justify-center gap-3">
              <Link href="/signup" className="px-6 py-3 rounded-md font-semibold bg-white text-black hover:bg-gray-200">
                Sign up free
              </Link>
              <a href="#features" className="px-6 py-3 rounded-md font-semibold border border-gray-800 text-white hover:bg-gray-900">
                Learn more
              </a>
            </div>
            <p className="mt-4 text-sm text-gray-400">No credit card required</p>
          </div>
        </section>

        {/* Features Grid */}
        <section id="features" className="py-10 md:py-16">
          <div className="grid gap-6 md:grid-cols-3">
            <div className="rounded-xl border border-gray-800 bg-black/30 p-6">
              <div className="text-xl font-semibold">AI Summaries</div>
              <p className="mt-2 text-gray-300">
                Get concise, high‑quality summaries generated by AI—no more skimming endless articles.
              </p>
            </div>
            <div className="rounded-xl border border-gray-800 bg-black/30 p-6">
              <div className="text-xl font-semibold">Smart Categories</div>
              <p className="mt-2 text-gray-300">
                Explore curated topics tailored to your interests with one‑click updates.
              </p>
            </div>
            <div className="rounded-xl border border-gray-800 bg-black/30 p-6">
              <div className="text-xl font-semibold">Source Transparency</div>
              <p className="mt-2 text-gray-300">
                Every summary links back to its original sources for full context and credibility.
              </p>
            </div>
          </div>
        </section>

        {/* Secondary CTA */}
        <section className="py-12 md:py-16 text-center">
          <div className="mx-auto max-w-2xl">
            <h2 className="text-2xl md:text-3xl font-bold">Start your smarter news routine today</h2>
            <p className="mt-3 text-gray-300">
              Join readers who get more value in less time with an intelligent daily digest.
            </p>
            <div className="mt-6">
              <Link href="/signup" className="px-6 py-3 rounded-md font-semibold bg-white text-black hover:bg-gray-200">
                Create your account
              </Link>
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-gray-800/60 py-6 text-center text-gray-400 text-sm">
        {new Date().getFullYear()} AI News Curator. All rights reserved.
      </footer>
    </div>
  );
}